name: atom_dart_lang_experimental
version: 0.0.1
description: An experimental Dart plugin for Atom.
homepage: https://github.com/dart-atom/dart-lang-experimental

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  logging: ^0.11.0
  markdown: ^0.7.0

dev_dependencies:
  grinder: ^0.7.0
  html: ^0.12.0
  test: ^0.12.0
