name: atom_dartlang
version: 0.3.7
description: An experimental Dart plugin for Atom.
homepage: https://github.com/dart-atom/dartlang
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  frappe: ^0.4.0
  logging: ^0.11.0
  markdown: ^0.7.0
dev_dependencies:
  grinder: ^0.7.0
  html: ^0.12.0
  pub_semver: ^1.2.1
  test: ^0.12.0
