name: atom_dartlang
version: 0.4.15
description: A Dart plugin for Atom.
homepage: https://github.com/dart-atom/dartlang

environment:
  sdk: '>=1.9.0 <2.0.0'

dependencies:
  # atom:
  #   git: https://github.com/dart-atom/atom.dart.git
  haikunator: ^0.1.0
  js: 0.6.0-beta.7
  logging: ^0.11.0
  markdown: ^0.8.0
  pub_semver: ^1.2.1
  usage: ^1.0.0
  vm_service_lib: 0.0.7
  yaml: ^2.0.0

dev_dependencies:
  grinder: ^0.8.0+1
  html: ^0.12.0
  test: ^0.12.0
  which: ^0.1.0
