name: atom_dartlang
version: 0.4.4
description: A Dart plugin for Atom.
homepage: https://github.com/dart-atom/dartlang

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  frappe: ^0.4.0
  haikunator: ^0.1.0
  logging: ^0.11.0
  markdown: ^0.8.0
  pub_semver: ^1.2.1
  usage: ^1.0.0
  yaml: ^2.0.0

dev_dependencies:
  grinder: ^0.7.0
  html: ^0.12.0
  test: ^0.12.0
